# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  # api:
  #   image: browsergame-api
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=Production
  #     - ASPNETCORE_URLS=http://+:80
  client:
    container_name: unchartedlands
    image: unchartedlands
    env_file: .env
    ports:
      - 4000:3000
    environment:
      ENVIRONMENT: Development
    depends_on:
      - postgres
  # cache:
  #   image: redis
  #   ports:
  #     - '6379:6379'
  postgres:
    image: postgres
    restart: always
    ports:
      - 6543:5432
    environment:
      POSTGRES_USER: postgres # The PostgreSQL user (useful to connect to the database)
      POSTGRES_PASSWORD: 1234 # The PostgreSQL password (useful to connect to the database)
      POSTGRES_DB: unchartedlands # The PostgreSQL default database (automatically created at first launch)