-- AlterTable
ALTER TABLE "Biome" ALTER COLUMN "foodModifier" SET DEFAULT 1,
ALTER COLUMN "oreModifier" SET DEFAULT 1,
ALTER COLUMN "plotAreaMax" SET DEFAULT 50,
ALTER COLUMN "plotAreaMin" SET DEFAULT 30,
ALTER COLUMN "plotsMax" SET DEFAULT 10,
ALTER COLUMN "plotsMin" SET DEFAULT 1,
ALTER COLUMN "solarModifier" SET DEFAULT 1,
ALTER COLUMN "stoneModifier" SET DEFAULT 1,
ALTER COLUMN "waterModifier" SET DEFAULT 1,
ALTER COLUMN "windModifier" SET DEFAULT 1,
ALTER COLUMN "woodModifier" SET DEFAULT 1;
